#!/usr/bin/env bash

while getopts ":f:" file; do
    case ${file} in
        f)
            ~/Desktop/brainfuck/build/brainfuck "./${OPTARG}"
            ;;
        ?)
            echo "Invalid option ${file}" >&2
            exit 1;
            ;;
    esac
done